/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.0).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import java.time.LocalDate;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;
import io.swagger.model.CalendarResults;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-02-20T18:32:34.907Z")

@Api(value = "calendar", description = "the calendar API")
public interface CalendarApi {

    @ApiOperation(value = "returns availability info for the given period", nickname = "calendarHotelIdGet", notes = "", response = CalendarResults.class, authorizations = {
        @Authorization(value = "api_key")
    }, tags={ "Calendar data", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Calendar availabilities information", response = CalendarResults.class),
        @ApiResponse(code = 401, message = "Unauthorized - The supplied API key does not allow you to access this resource (hotel/room type/rate plan)"),
        @ApiResponse(code = 404, message = "Resource not found") })
    @RequestMapping(value = "/calendar/{hotelId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<CalendarResults> calendarHotelIdGet(@ApiParam(value = "ID of the hotel",required=true) @PathVariable("hotelId") String hotelId,@NotNull @ApiParam(value = "Start date of the requested timespan", required = true) @Valid @RequestParam(value = "start", required = true) LocalDate start,@NotNull @ApiParam(value = "End date of the requested timespan", required = true) @Valid @RequestParam(value = "end", required = true) LocalDate end,@ApiParam(value = "ID of the room type") @Valid @RequestParam(value = "roomId", required = false) String roomId,@ApiParam(value = "ID of the rate plan") @Valid @RequestParam(value = "rateplanId", required = false) String rateplanId,@ApiParam(value = "Number of adults (if known)") @Valid @RequestParam(value = "nbAdults", required = false) Integer nbAdults,@ApiParam(value = "Number of children (if known)") @Valid @RequestParam(value = "nbChildren", required = false) Integer nbChildren,@ApiParam(value = "Number of infants (if known)") @Valid @RequestParam(value = "nbInfants", required = false) Integer nbInfants);

}
