/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.0).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.HotelConfig;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-02-20T18:32:34.907Z")

@Api(value = "config", description = "the config API")
public interface ConfigApi {

    @ApiOperation(value = "returns the front-end configuration for a given hotel", nickname = "configHotelIdGet", notes = "", response = HotelConfig.class, authorizations = {
        @Authorization(value = "api_key")
    }, tags={ "Descriptive info", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Hotel configuration", response = HotelConfig.class),
        @ApiResponse(code = 401, message = "Unauthorized - The supplied API key does not allow you to access this resource (hotel/room type/rate plan)"),
        @ApiResponse(code = 404, message = "Resource not found") })
    @RequestMapping(value = "/config/{hotelId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<HotelConfig> configHotelIdGet(@ApiParam(value = "ID of the hotel",required=true) @PathVariable("hotelId") String hotelId);

}
