/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.0).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.HotelDescriptiveInfo;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-02-20T18:32:34.907Z")

@Api(value = "descriptive-info", description = "the descriptive-info API")
public interface DescriptiveInfoApi {

    @ApiOperation(value = "returns the descriptive info for a given hotel", nickname = "descriptiveInfoLangHotelIdGet", notes = "For more information about the code used in the returned data, please see the links below: - for the hotel services/amenities see the [Hotel Amenity Code (HAC)](https://tourisoft.atlassian.net/wiki/spaces/HOT/pages/4325557/Hotel+Amenity+Code+HAC) list - for the room amenities see the [Room Amenity Type (RMA)](https://tourisoft.atlassian.net/wiki/spaces/HOT/pages/4325585/Room+Amenity+Type+RMA) list", response = HotelDescriptiveInfo.class, authorizations = {
        @Authorization(value = "api_key")
    }, tags={ "Descriptive info", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Hotel descriptive info", response = HotelDescriptiveInfo.class),
        @ApiResponse(code = 401, message = "Unauthorized - The supplied API key does not allow you to access this resource (hotel/room type/rate plan)"),
        @ApiResponse(code = 404, message = "Resource not found") })
    @RequestMapping(value = "/descriptive-info/{lang}/{hotelId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<HotelDescriptiveInfo> descriptiveInfoLangHotelIdGet(@ApiParam(value = "Language",required=true, allowableValues = "\"en\", \"fr\", \"de\", \"nl\", \"es\", \"it\"") @PathVariable("lang") String lang,@ApiParam(value = "ID of the hotel",required=true) @PathVariable("hotelId") String hotelId);

}
