/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.0).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import java.time.LocalDate;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;
import io.swagger.model.ServiceResults;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-02-20T18:32:34.907Z")

@Api(value = "services", description = "the services API")
public interface ServicesApi {

    @ApiOperation(value = "returns the available services for the given search parameters", nickname = "servicesLangHotelIdGet", notes = "", response = ServiceResults.class, authorizations = {
        @Authorization(value = "api_key")
    }, tags={ "Availabilities", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Available services", response = ServiceResults.class),
        @ApiResponse(code = 401, message = "Unauthorized - The supplied API key does not allow you to access this resource (hotel/room type/rate plan)"),
        @ApiResponse(code = 404, message = "Resource not found") })
    @RequestMapping(value = "/services/{lang}/{hotelId}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<ServiceResults> servicesLangHotelIdGet(@ApiParam(value = "Language",required=true, allowableValues = "\"en\", \"fr\", \"de\", \"nl\", \"es\", \"it\"") @PathVariable("lang") String lang,@ApiParam(value = "ID of the hotel",required=true) @PathVariable("hotelId") String hotelId,@NotNull @ApiParam(value = "ID of the user session", required = true) @Valid @RequestParam(value = "sessionId", required = true) String sessionId,@NotNull @ApiParam(value = "ID of the room type", required = true) @Valid @RequestParam(value = "roomId", required = true) String roomId,@NotNull @ApiParam(value = "ID of the rate plan", required = true) @Valid @RequestParam(value = "rateplanId", required = true) String rateplanId,@NotNull @ApiParam(value = "Start date of the stay (date of arrival)", required = true) @Valid @RequestParam(value = "start", required = true) LocalDate start,@NotNull @ApiParam(value = "End date of the stay (date of departure)", required = true) @Valid @RequestParam(value = "end", required = true) LocalDate end,@NotNull @ApiParam(value = "Number of adults for the stay", required = true) @Valid @RequestParam(value = "nbAdults", required = true) Integer nbAdults,@NotNull @ApiParam(value = "Number of children for the stay", required = true) @Valid @RequestParam(value = "nbChildren", required = true) Integer nbChildren,@NotNull @ApiParam(value = "Number of infants for the stay", required = true) @Valid @RequestParam(value = "nbInfants", required = true) Integer nbInfants);

}
